package com.example.simple_api.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

/**
 * Represents a row in the 'quotes' table.
 * Uses Lombok's @Data annotation to automatically generate
 * getters, setters, and other boilerplate methods.
 */
@Entity
@Data
@Table(name = "quotes")
public class Quotes {
    
    // Primary Key, automatically generated by the database (PostgreSQL SERIAL type)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The actual quote text
    @Column(name = "quote", nullable = false, columnDefinition = "TEXT")
    private String quoteText;

}